### ISSUE TITLE
Task failed but does not return traceback

### ISSUE THREAD

**Issue by rywillia** [rywillia/blaster#10]
With the latest release of blaster v0.1.3. If a task method call fails, it captures the traceback and sets it. Just that data is not being returned back to the user at the end of blastoff method.

```
2017-08-17 10:30:34,187 INFO [blaster.blast.blastoff:47] ..............................
2017-08-17 10:30:34,188 INFO [blaster.blast.blastoff:48] START: BLASTER PREPARATION
2017-08-17 10:30:34,188 INFO [blaster.blast.blastoff:49] ..............................
2017-08-17 10:30:34,189 INFO [blaster.blast.blastoff:68] 1. TASK ~ House, METHODS: ['foundation', 'frame', 'roof', 'furnish', 'enjoy']
2017-08-17 10:30:34,190 INFO [blaster.blast.blastoff:68] 2. TASK ~ House, METHODS: ['foundation', 'frame', 'roof', 'furnish', 'post_build_tasks', 'enjoy']
2017-08-17 10:30:34,190 INFO [blaster.blast.blastoff:68] 3. TASK ~ House, METHODS: ['foundation', 'frame', 'roof', 'furnish', 'post_build_tasks', 'enjoy']
2017-08-17 10:30:34,191 INFO [blaster.blast.blastoff:68] 4. TASK ~ House, METHODS: ['foundation', 'frame', 'roof', 'furnish', 'post_build_tasks', 'enjoy']
2017-08-17 10:30:34,191 INFO [blaster.blast.blastoff:68] 5. TASK ~ House, METHODS: ['foundation', 'frame', 'roof', 'furnish', 'post_build_tasks', 'enjoy']
2017-08-17 10:30:34,191 INFO [blaster.blast.blastoff:73] ..............................
2017-08-17 10:30:34,191 INFO [blaster.blast.blastoff:74] END: BLASTER PREPARATION
2017-08-17 10:30:34,192 INFO [blaster.blast.blastoff:75] ..............................
2017-08-17 10:30:34,193 INFO [blaster.blast.blastoff:81] ..............................
2017-08-17 10:30:34,193 INFO [blaster.blast.blastoff:82] START: BLASTER BLAST OFF
2017-08-17 10:30:34,193 INFO [blaster.blast.blastoff:83] ..............................
2017-08-17 10:30:34,193 INFO [blaster.blast.blastoff:92] Total processes used by blaster is 5.
2017-08-17 10:30:34,195 INFO [blaster.foundation:21] Building the foundation for contemporary house..
2017-08-17 10:30:34,198 INFO [blaster.foundation:21] Building the foundation for colonial house..
2017-08-17 10:30:34,198 INFO [blaster.foundation:21] Building the foundation for cape house..
2017-08-17 10:30:34,198 INFO [blaster.foundation:21] Building the foundation for ranch house..
Traceback (most recent call last):
  File "/home/rywillia/github/blaster/blaster/engine/processor.py", line 49, in run
    getattr(task_obj, method)()
  File "/home/rywillia/github/blaster/examples/build_houses.py", line 23, in foundation
    raise Exception('Cannot build!')
Exception: Cannot build!
2017-08-17 10:30:34,199 INFO [blaster.foundation:21] Building the foundation for split house..
2017-08-17 10:30:35,197 INFO [blaster.frame:27] Frame the house for contemporary house..
2017-08-17 10:30:35,200 INFO [blaster.frame:27] Frame the house for colonial house..
2017-08-17 10:30:35,200 INFO [blaster.frame:27] Frame the house for cape house..
2017-08-17 10:30:35,200 INFO [blaster.frame:27] Frame the house for split house..
2017-08-17 10:30:36,198 INFO [blaster.roof:31] Roof the house for contemporary house..
2017-08-17 10:30:36,201 INFO [blaster.roof:31] Roof the house for cape house..
2017-08-17 10:30:36,201 INFO [blaster.roof:31] Roof the house for colonial house..
2017-08-17 10:30:36,201 INFO [blaster.roof:31] Roof the house for split house..
2017-08-17 10:30:37,200 INFO [blaster.furnish:35] Furnish the house for contemporary house..
2017-08-17 10:30:37,202 INFO [blaster.furnish:35] Furnish the house for cape house..
2017-08-17 10:30:37,202 INFO [blaster.furnish:35] Furnish the house for split house..
2017-08-17 10:30:37,203 INFO [blaster.furnish:35] Furnish the house for colonial house..
2017-08-17 10:30:38,201 INFO [blaster.enjoy:39] Enjoy your new contemporary house :)
2017-08-17 10:30:38,203 INFO [blaster.post_build_tasks:43] Perform post building tasks for split house..
2017-08-17 10:30:38,203 INFO [blaster.post_build_tasks:43] Perform post building tasks for cape house..
2017-08-17 10:30:38,204 INFO [blaster.post_build_tasks:43] Perform post building tasks for colonial house..
2017-08-17 10:30:39,204 INFO [blaster.enjoy:39] Enjoy your new cape house :)
2017-08-17 10:30:39,204 INFO [blaster.enjoy:39] Enjoy your new split house :)
2017-08-17 10:30:39,205 INFO [blaster.enjoy:39] Enjoy your new colonial house :)
2017-08-17 10:30:40,208 INFO [blaster.blast.blastoff:148] Total blast off duration: 0h:0m:6s
2017-08-17 10:30:40,208 INFO [blaster.blast.blastoff:150] ..............................
2017-08-17 10:30:40,209 INFO [blaster.blast.blastoff:151] END: BLASTER BLAST OFF
2017-08-17 10:30:40,209 INFO [blaster.blast.blastoff:152] ..............................
[   {   '_id': '2ba7f0dc-6cf7-4db8-8b1f-762ec351709c',
        'methods': [   'foundation',
                       'frame',
                       'roof',
                       'furnish',
                       'post_build_tasks',
                       'enjoy'],
        'name': 'House 4',
        'status': 1,
        'style': 'ranch',
        'task': <class '__main__.House'>},
    {   'methods': ['foundation', 'frame', 'roof', 'furnish', 'enjoy'],
        'name': 'House 1',
        'status': 0,
        'style': 'contemporary',
        'task': <class '__main__.House'>},
    {   '_id': '60eaa333-6577-4cbc-aac5-1bc339b159e8',
        'methods': [   'foundation',
                       'frame',
                       'roof',
                       'furnish',
                       'post_build_tasks',
                       'enjoy'],
        'name': 'House 5',
        'status': 0,
        'style': 'split',
        'task': <class '__main__.House'>},
    {   '_id': 'df061d03-0080-486e-8379-42359b2134b2',
        'methods': [   'foundation',
                       'frame',
                       'roof',
                       'furnish',
                       'post_build_tasks',
                       'enjoy'],
        'name': 'House 2',
        'status': 0,
        'style': 'cape',
        'task': <class '__main__.House'>},
    {   '_id': '0641fb02-4d22-454d-abd4-63232dca4801',
        'methods': [   'foundation',
                       'frame',
                       'roof',
                       'furnish',
                       'post_build_tasks',
                       'enjoy'],
        'name': 'House 3',
        'status': 0,
        'style': 'colonial',
        'task': <class '__main__.House'>}]
```
Need to determine why this data is not being returned back properly.

**Comment by rywillia** [comment]
Traceback is now saved to the results of each task.

```
2017-08-19 09:17:03,107 INFO [blaster.blast.blastoff:47] ..............................
2017-08-19 09:17:03,107 INFO [blaster.blast.blastoff:48] START: BLASTER PREPARATION
2017-08-19 09:17:03,107 INFO [blaster.blast.blastoff:49] ..............................
2017-08-19 09:17:03,108 INFO [blaster.blast.blastoff:68] 1. TASK ~ House, METHODS: ['foundation', 'frame', 'roof', 'furnish', 'enjoy']
2017-08-19 09:17:03,108 INFO [blaster.blast.blastoff:68] 2. TASK ~ House, METHODS: ['foundation', 'frame', 'roof', 'furnish', 'post_build_tasks', 'enjoy']
2017-08-19 09:17:03,109 INFO [blaster.blast.blastoff:68] 3. TASK ~ House, METHODS: ['foundation', 'frame', 'roof', 'furnish', 'post_build_tasks', 'enjoy']
2017-08-19 09:17:03,109 INFO [blaster.blast.blastoff:68] 4. TASK ~ House, METHODS: ['foundation', 'frame', 'roof', 'furnish', 'post_build_tasks', 'enjoy']
2017-08-19 09:17:03,109 INFO [blaster.blast.blastoff:68] 5. TASK ~ House, METHODS: ['foundation', 'frame', 'roof', 'furnish', 'post_build_tasks', 'enjoy']
2017-08-19 09:17:03,109 INFO [blaster.blast.blastoff:73] ..............................
2017-08-19 09:17:03,110 INFO [blaster.blast.blastoff:74] END: BLASTER PREPARATION
2017-08-19 09:17:03,110 INFO [blaster.blast.blastoff:75] ..............................
2017-08-19 09:17:03,111 INFO [blaster.blast.blastoff:81] ..............................
2017-08-19 09:17:03,111 INFO [blaster.blast.blastoff:82] START: BLASTER BLAST OFF
2017-08-19 09:17:03,111 INFO [blaster.blast.blastoff:83] ..............................
2017-08-19 09:17:03,112 INFO [blaster.blast.blastoff:92] Total processes used by blaster is 5.
2017-08-19 09:17:03,117 INFO [blaster.foundation:21] Building the foundation for contemporary house..
2017-08-19 09:17:03,117 INFO [blaster.foundation:21] Building the foundation for cape house..
2017-08-19 09:17:03,118 INFO [blaster.foundation:21] Building the foundation for colonial house..
2017-08-19 09:17:03,119 INFO [blaster.foundation:21] Building the foundation for ranch house..
2017-08-19 09:17:03,119 INFO [blaster.foundation:21] Building the foundation for split house..
2017-08-19 09:17:04,118 INFO [blaster.frame:25] Frame the house for contemporary house..
2017-08-19 09:17:04,118 INFO [blaster.frame:25] Frame the house for cape house..
2017-08-19 09:17:04,118 INFO [blaster.frame:25] Frame the house for colonial house..
2017-08-19 09:17:04,120 INFO [blaster.frame:25] Frame the house for split house..
2017-08-19 09:17:04,120 INFO [blaster.frame:25] Frame the house for ranch house..
Traceback (most recent call last):
  File "/Users/ryan/PycharmProjects/blaster/blaster/engine/processor.py", line 49, in run
    getattr(task_obj, method)()
  File "/Users/ryan/PycharmProjects/blaster/examples/build_houses.py", line 27, in frame
    raise Exception('No materials for framing ranch house today.')
Exception: No materials for framing ranch house today.
2017-08-19 09:17:05,120 INFO [blaster.roof:31] Roof the house for cape house..
2017-08-19 09:17:05,120 INFO [blaster.roof:31] Roof the house for contemporary house..
2017-08-19 09:17:05,120 INFO [blaster.roof:31] Roof the house for colonial house..
2017-08-19 09:17:05,122 INFO [blaster.roof:31] Roof the house for split house..
2017-08-19 09:17:06,122 INFO [blaster.furnish:35] Furnish the house for contemporary house..
2017-08-19 09:17:06,122 INFO [blaster.furnish:35] Furnish the house for colonial house..
2017-08-19 09:17:06,122 INFO [blaster.furnish:35] Furnish the house for cape house..
Traceback (most recent call last):
  File "/Users/ryan/PycharmProjects/blaster/blaster/engine/processor.py", line 49, in run
    getattr(task_obj, method)()
  File "/Users/ryan/PycharmProjects/blaster/examples/build_houses.py", line 37, in furnish
    raise Exception('No furniture to furnish cape house today.')
Exception: No furniture to furnish cape house today.
2017-08-19 09:17:06,123 INFO [blaster.furnish:35] Furnish the house for split house..
2017-08-19 09:17:07,123 INFO [blaster.post_build_tasks:45] Perform post building tasks for colonial house..
2017-08-19 09:17:07,123 INFO [blaster.enjoy:41] Enjoy your new contemporary house :)
2017-08-19 09:17:07,124 INFO [blaster.post_build_tasks:45] Perform post building tasks for split house..
2017-08-19 09:17:08,125 INFO [blaster.enjoy:41] Enjoy your new split house :)
2017-08-19 09:17:08,125 INFO [blaster.enjoy:41] Enjoy your new colonial house :)
2017-08-19 09:17:09,129 INFO [blaster.blast.blastoff:148] Total blast off duration: 0h:0m:6s
2017-08-19 09:17:09,129 INFO [blaster.blast.blastoff:150] ..............................
2017-08-19 09:17:09,130 INFO [blaster.blast.blastoff:151] END: BLASTER BLAST OFF
2017-08-19 09:17:09,130 INFO [blaster.blast.blastoff:152] ..............................
[   {   '_id': '719852b7-c6ad-46f4-8f97-90ed20ab490e',
        'methods': [   {   'name': 'foundation', 'status': 0},
                       {   'name': 'frame',
                           'status': 1,
                           'traceback': [   '  File "/Users/ryan/PycharmProjects/blaster/blaster/engine/processor.py", line 49, in run\n    getattr(task_obj, method)()\n',
                                            '  File "/Users/ryan/PycharmProjects/blaster/examples/build_houses.py", line 27, in frame\n    raise Exception(\'No materials for framing ranch house today.\')\n']}],
        'name': 'House 4',
        'status': 1,
        'style': 'ranch',
        'task': <class '__main__.House'>},
    {   'methods': [   {   'name': 'foundation', 'status': 0},
                       {   'name': 'frame', 'status': 0},
                       {   'name': 'roof', 'status': 0},
                       {   'name': 'furnish',
                           'status': 1,
                           'traceback': [   '  File "/Users/ryan/PycharmProjects/blaster/blaster/engine/processor.py", line 49, in run\n    getattr(task_obj, method)()\n',
                                            '  File "/Users/ryan/PycharmProjects/blaster/examples/build_houses.py", line 37, in furnish\n    raise Exception(\'No furniture to furnish cape house today.\')\n']}],
        'name': 'House 2',
        'status': 1,
        'style': 'cape',
        'task': <class '__main__.House'>},
    {   'methods': [   {   'name': 'foundation', 'status': 0},
                       {   'name': 'frame', 'status': 0},
                       {   'name': 'roof', 'status': 0},
                       {   'name': 'furnish', 'status': 0},
                       {   'name': 'enjoy', 'status': 0}],
        'name': 'House 1',
        'status': 0,
        'style': 'contemporary',
        'task': <class '__main__.House'>},
    {   '_id': '53d13f29-bd86-480f-87d9-a621b4b5cbe1',
        'methods': [   {   'name': 'foundation', 'status': 0},
                       {   'name': 'frame', 'status': 0},
                       {   'name': 'roof', 'status': 0},
                       {   'name': 'furnish', 'status': 0},
                       {   'name': 'post_build_tasks', 'status': 0},
                       {   'name': 'enjoy', 'status': 0}],
        'name': 'House 5',
        'status': 0,
        'style': 'split',
        'task': <class '__main__.House'>},
    {   '_id': '21e4d6dc-7fe2-4434-9c6f-df6eb8314c5b',
        'methods': [   {   'name': 'foundation', 'status': 0},
                       {   'name': 'frame', 'status': 0},
                       {   'name': 'roof', 'status': 0},
                       {   'name': 'furnish', 'status': 0},
                       {   'name': 'post_build_tasks', 'status': 0},
                       {   'name': 'enjoy', 'status': 0}],
        'name': 'House 3',
        'status': 0,
        'style': 'colonial',
        'task': <class '__main__.House'>}]
```
